### ISSUE TITLE
Uses tiny buffers when attempting to decompress

### ISSUE THREAD

**Issue by Keno** [bicycle1885/TranscodingStreams.jl#1]
I tried to use this package to decompress a large bzip2 file. Unfortunately, it would hang during decompression. This is because, after the first call to the decompression routine, all subsequent calls would use an output buffer size of 1, which is obviously not particularly efficient. I'd recommend 4k at least, though more may be appropriate as well.

**Comment by bicycle1885** [comment]
Hi,

I couldn't reproduce this problem. I decompressed a bzip2-compressed file with ~128MB (~10,000,000 lines) using the bzip2 command and CodecBzip2.jl. The decompression throughputs are almost the same:

```console
~/.j/v/CodecBzip2 (master|…) $ time cat gvcf.bz2 | bzip2 -d | wc -l
       30.38 real         0.00 user         0.09 sys
 9984621
```
```julia
using CodecBzip2
@time open(countlines, Bzip2DecompressionStream, "gvcf.bz2")
```
```console
~/.j/v/CodecBzip2 (master|…) $ julia6 test.jl
 30.205409 seconds (201.94 k allocations: 7.671 MiB)
```

Can you describe more details on the problem or correct me if I'm misunderstanding you?

**Comment by Keno** [comment]
I used `readall` to read the file in, then `transcode` on the entire buffer.
