### ISSUE TITLE
not freeing buffers

### ISSUE THREAD

**Issue by pevnak** [bicycle1885/TranscodingStreams.jl#37]
Hello,

Is it possible that repeated use of TranscodingStreams is consuming memory? In my application I have data files (FlatBuffers) gzipped and stored in network storage. I load the content of the file to the memory, unpack them, and parse the FlatBuffers as
```
open(file,"r") do fid
    Base.read(CodecZlib.GzipDecompressorStream(fid))
  end
```

When I do this I seem how the memory of the machine is depleted until the machine crash. When I unpack the files on the disk and use the same mechanism, the memory is preserved. Reading the documentation on the web, I have figured about that you are using some buffers. Is there a way, how I can flush them?

**Comment by bicycle1885** [comment]
A TranscodingStream object will free memory of codec only when it is closed or when it throws an exception. So, you need to explicitly close a stream just like a usual file. Your code closes the file, but not the transcoding stream. You should write it in this way:
```julia
stream = GzipDecompressorStream(open(file, "r"))
try
    data = read(stream)
finally
    close(stream)
end
```

**Comment by pevnak** [comment]
Thanks a lot for the explanation. I will try, how it will work.
