### ISSUE TITLE
add position()

### ISSUE THREAD

**Issue by alyst** [bicycle1885/TranscodingStreams.jl#62]
It would be nice to have `Base.position(io::TranscodingStream)` to return the current position in the transcoded stream.
There's already `state.total_out`, so it should not be impossible to keep track of the transcoded bytes since the last reset (+myabe adjust it w.r.t `unread()`).

*The use case.*
I came across this issue once again when trying to convert [MLDatasets.jl](https://github.com/JuliaML/MLDatasets.jl) to use CodecZlib.jl instead of the aging GZip.jl.
The gzipped files there are collections of images, each image occupying the same size. So, given image index, we can tell its exact position in the decoding stream.
When implementing `readimages(io, image_indices::AbstractVector)`, it was natural to define `readimage(io, image_index)`.
To work, `readimage()` just needs to know the current stream position, so that it can calculate how many bytes to skip to get to the specified image.
Without `position(io)` one would have to keep track of this information somewhere externally, which looks like an unnecessary complication to me.

**Comment by damiendr** [comment]
I would also like having position() on transcoding streams, so that I could use them with a parser that does something like this:
```julia
offset = position(io)
len = read(io, UInt32)
while position(io) < offset + len
   read_item(io)
end
```

**Comment by zgornel** [comment]
`position` works however one has to flush the stream first:
```julia
julia> using TranscodingStreams, Serialization
       fid = TranscodingStream(Noop(), open("./__deleteme__.bin","w"))
       serialize(fid, 1)
       @show position(fid)
       flush(fid)
       @show position(fid)                                                                                                                       
# position(fid) = -9                                                                                                                               
# position(fid) = 9                                                                                                                                
9                           
```

**Comment by laborg** [comment]
Looking at CSV.jl again, it appears that implementing `seek` would be necessary to. 

@bicycle1885 : I don't want to pressure you, but do you know when you will find time? With this information dependent packages  could easier decide whether or not to create an intermediate work around. (e.g. load everything into a IOBuffer for RDatasets).
