### ISSUE TITLE
Make struct TranscodingStream mutable

### ISSUE THREAD

**Issue by simonschoelly** [bicycle1885/TranscodingStreams.jl#66]
I'm not that familiar with the code here, so maybe I got this wrong. I'm trying to get `GraphIO.jl` running on Julia 0.7.
Apparently the code there feeds a `TranscodingStream` object to the constructor `StreamReader(input::IO)` from `EzXML.jl` 
The problem is now, that EzXML then calls `context = pointer_from_objref(input)` which is a problem because `pointer_from_objref` can only be used on immutable objects. 

Is this something that can be fixed here? Or should a TranscodingStream not be combined with a StreamReader?

**Comment by bicycle1885** [comment]
I think this can be fixed on EzXML's side. I'll take a look today or tomorrow. Thank you for reporting it.

**Comment by bicycle1885** [comment]
Good news. Now `TranscodingStream` and `StreamReader` can work together with this change https://github.com/bicycle1885/EzXML.jl/pull/94. I'm going to release it soon after adding some touch-ups, but if you want to try it now, please check out the master branch of EzXML.jl.

**Comment by simonschoelly** [comment]
It works for GraphIO.jl  ow. Thanks!
