### ISSUE TITLE
An example needed for daisy chaining of TranscodingStreams

### ISSUE THREAD

**Issue by sambitdash** [bicycle1885/TranscodingStreams.jl#8]
Many times in real life the data is encoded serially. For example, post encryption one would like to base64 encode the stream. And the decoding should be the reverse sequence. It's not clear from the example if TranscodingStream can be passed as IO into another TranscodingStream. 

The sources in BufferedInputStream could be used for these purposes easily.

**Comment by bicycle1885** [comment]
Do you mean something like #9 ?

**Comment by bicycle1885** [comment]
Fixed by #9.

**Comment by bicycle1885** [comment]
@sambitdash JFYI, I've made a package for base 16 and base 64 encoding: https://github.com/bicycle1885/CodecBase.jl, which is reasonably fast compared to other implementations.

**Comment by sambitdash** [comment]
This is indeed awesome!!! Recently we were working on a similar code for the base package which may no longer be needed once you have Transcodec packages. You can see a few benchmarks in the pull request: https://github.com/JuliaLang/julia/pull/23267 

One particular benchmark that may interest you is when you do not reject the input for bad input but sanitize it. I could clock 12ms for a 10MB size array on i7 processor with 8GB RAM 64-bit machine. For the other implementations the timings were 40 to 45 ms.  https://github.com/JuliaLang/julia/pull/23267#issuecomment-323522350

@StefanKarpinski  you may be interested in this stream implementation over adding this functionality into base as you raised in https://github.com/JuliaLang/julia/issues/23161

**Comment by sambitdash** [comment]
@bicycle1885 I have not reviewed the code for `CodecBase` but I am assuming you have provision to ignore a set of characters in the filter implementation. For example, in ASCII codecs it's not uncommon to see CR-LFs or tabs or spaces in the text stream. 

Typical scenarios, MIME encoded mail messages are sent in base64 encoding but most having a width of 80 characters, the same is true for certificate files like DER and CER. Acrobat PDF files though do not have it as required most writers typically put a LF at the 80th character. Reading with `readline()` and then converting in chunks to binary is an option. But unnecessary overhead for a developer. If you can support tabs `hexdump` output can be supported as well. So if a developer has a flexibility to provide an ignore list of characters, it can be very beneficial.

**Comment by bicycle1885** [comment]
I've pushed a commit that implements the idea: https://github.com/bicycle1885/CodecBase.jl/commit/c89b027334ffdcb78093bce4fb57f8e10a48c974. I'm not sure the best way and so it now ignores whitespaces by default. Of course, you can choose any character set you want to ignore by specifying the `ignore` option to the `Base64Decoder`.

**Comment by bicycle1885** [comment]
In fact, on my machine, the `base64decode` of the standard library seems to be ridiculously slow.

Julia 0.6:
```
julia> sizeof(data)
286180

julia> @benchmark transcode(Base64Decoder(), data)
BenchmarkTools.Trial:
  memory estimate:  490.31 KiB
  allocs estimate:  19
  --------------
  minimum time:     372.894 μs (0.00% GC)
  median time:      561.580 μs (0.00% GC)
  mean time:        594.615 μs (6.84% GC)
  maximum time:     4.291 ms (68.99% GC)
  --------------
  samples:          8379
  evals/sample:     1

julia> @benchmark base64decode(data)
BenchmarkTools.Trial:
  memory estimate:  1022.61 KiB
  allocs estimate:  17
  --------------
  minimum time:     107.637 ms (0.00% GC)
  median time:      110.100 ms (0.00% GC)
  mean time:        111.497 ms (0.00% GC)
  maximum time:     128.912 ms (0.00% GC)
  --------------
  samples:          45
  evals/sample:     1

```

Python 3.5.2:
```
In [13]: len(data)
Out[13]: 286180

In [14]: %timeit base64.decodebytes(data)
1.16 ms ± 14.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

```

**Comment by sambitdash** [comment]
This is very encouraging output indeed. You may also want to look at the memory estimate of your code:
```
  memory estimate:  490.31 KiB
  allocs estimate:  19
```
For a 286K input and an output should be generated of size `3/4*286 = 214K`. Which means there is an overhead of 276K bytes generated during temp computations. This can be attributed to intermediate buffers you actually need but many a times in Julia they could be due to type conversions. You may want to review your code to see if you need such additional buffers. 

On the case functionality, it may be a good idea to raise an issue so that it's recorded and can be worked upon later.

Once your `base64` code is stable the same ignore character logic may be helpful for `base16 (binhex)` codec as well. I have seen Adobe PDF content stream adds newlines for every 80th character input. 

One last encoding in this class which is used is called `base85` encoding. Though computationally it may be a bit harder to compute it encodes 5 bytes for each 4 bytes of input  unlike the ratio of (4:3) in `base64`. But the bigger concern is there are 4 non-standard minor variations:

https://en.wikipedia.org/wiki/Ascii85

I have implemented the Adobe version in my PDF parser code but the code is not great as I had just picked up Julia as a programming language. But you can get the logic. It's a byte-by-byte scanning code. 

https://github.com/sambitdash/PDFIO.jl/blob/9c8f210a0d768056c6307f5eb66980daa278b05e/src/CosStream.jl#L436
https://github.com/sambitdash/PDFIO.jl/blob/9c8f210a0d768056c6307f5eb66980daa278b05e/src/CosStream.jl#L480

Anyway, you can take a look at this encoding if you think it's a good addition to your base encodings.

**Comment by sambitdash** [comment]
Ignoring whitespaces and CR-LF by default is a good thing but one should have the flexibility of overriding that. Text encoding protocols add white spaced based on the underlying protocol like say MIME encoding in mail protocols transferred over SMTP.

**Comment by bicycle1885** [comment]
#11 reduces the memory allocation significantly (still not optimal, but much better).

Supporting Ascii85 is nice but it looks a little bit complicated. I'll rethink it later.

Also, the current decoders can take the `ignore` argument that can specify an arbitrary set of characters that will be ignored while decoding.

**Comment by sambitdash** [comment]
I have plans to move PDFIO to transcoding streams. I may be able to look at ASCII85 that time. But that may not happen immediately. If I do so I will send you a PR on the same.

**Comment by StefanKarpinski** [comment]
> @StefanKarpinski you may be interested in this stream implementation over adding this functionality into base as you raised in JuliaLang/julia#23161

Some sort of stream chaining approach here would be great – but sometimes I'm guessing just having `hex2bytes!` in base is simpler; no harm letting people have the option.
